-- Add selector_map column to agencies table
-- This stores the AI-generated JSON mapping of CSS selectors for each agency's form
ALTER TABLE public.agencies
ADD COLUMN IF NOT EXISTS selector_map JSONB;

COMMENT ON COLUMN public.agencies.selector_map IS 'AI-generated JSON map of CSS selectors for the agency application form. Generated by map_agency.js via Gemini Flash.';
