ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS height_cm INT,
ADD COLUMN IF NOT EXISTS bust_cm INT,
ADD COLUMN IF NOT EXISTS waist_cm INT,
ADD COLUMN IF NOT EXISTS hips_cm INT,
ADD COLUMN IF NOT EXISTS shoe_size_uk NUMERIC(3,1),
ADD COLUMN IF NOT EXISTS eye_color TEXT,
ADD COLUMN IF NOT EXISTS hair_color TEXT;
